Run block header validation e2e
keep-starknet-strange/raito pull request #113
Opened 2024-08-28 17:58 UTC by m-kus

This PR introduces `BlockHeader` structure which is a `Header` extended with the Merkle tree root. This structure is sufficient to do header-only validation and new `BlockHeaderValidator` trait allows to do that and update the chain state accordingly.

There is an accompanying integration test that checks `ChainState169 + BlockHeader170 = ChainState170`. This test has been written manually, but we should instead generate such tests via script, it will be useful to create regression tests in the future.

Finally, the main function is updated to perform block header validation, there is also a script that runs the program e2e, loading parameters from a json file and encoding them into field elements.

- [x] issue #96
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

2024-08-30 13:20 UTC, maciejka reviewed
In general I agree that having the ability to validate headers alone in the project is a valid goal. What I worry about is having to maintain extra infrastructure. They way it is written we need an extra struct, validate function and a script to run it, extra test data, and a script to build this data. Overall a second execution path in the project which we will need to maintain.

I would prefer to incorporate header validation in the main flow even at the cost of some extra data and ifs in the code. How making `Block` dual use struct that would contain header and either a list of transactions or transaction hash? Validation function would become slightly more complex but we would save on infrastructure duplication.

WDYT?

2024-08-30 13:40 UTC, m-kus commented
This is indeed a second path, but there are not just downsides :)

We can definitely make `Block` dual use struct and reuse (some) of the validation, but I'd argue that the current separation is cleaner and likely (I haven't measured though) reduces the # of steps, while merging two cases together will introduce more code. Maybe it's better to instead refactor the top level validation flow to reduce the overlap between full block/block header implementations?

As for the scripts and data - here I cannot think of a way to fully merge two cases. The key idea is that for block header validation you can do very lightweight requests with constant size response (probably we can even query batches from some data lake) and those responses are self-sufficient, i.e. no need to extend the data with other information (like we do for the full consensus client). But implementation wise it will likely to be the same Python file just with different CLI option.

2024-08-30 13:43 UTC, m-kus commented on scripts/data/felt_writer.py
> +# This module provides helpers for serializing Python objects into Cairo runner arguments (felts and arrays).
Yes, they provide ABI encoding/decoding functionality but that's specific to Starknet contracts.  
In our case we are cheating a bit by "looking under the hood" to see how types we are interested in are stored on the stack.

2024-08-30 15:46 UTC, maciejka commented
> This is indeed a second path, but there are not just downsides :)
> 
> We can definitely make `Block` dual use struct and reuse (some) of the validation, but I'd argue that the current separation is cleaner and likely (I haven't measured though) reduces the # of steps, while merging two cases together will introduce more code. Maybe it's better to instead refactor the top level validation flow to reduce the overlap between full block/block header implementations?

I can afford to sacrifice some steps (very little compared to the cost sha). 
Dual use block will require less code. 
In fact we will need even more modes of operation when we introduce utreexo, I mean in the end there will be at least:
* header verification
* block verification without utreexo
* full verification
* maybe even: block verification without scripts and utreexo

I would frame header vs full block verification in this context. 

> As for the scripts and data - here I cannot think of a way to fully merge two cases. The key idea is that for block header validation you can do very lightweight requests with constant size response (probably we can even query batches from some data lake) and those responses are self-sufficient, i.e. no need to extend the data with other information (like we do for the full consensus client). But implementation wise it will likely to be the same Python file just with different CLI option.

If header case data script would use getheader instead of getblock + getrawtransactions.

Let's have a call to continue this discussion.

2024-09-02 09:59 UTC, maciejka requested changes

2024-09-02 09:59 UTC, maciejka commented on src/types/block.cairo
>      pub txs: Span<Transaction>,
This should be either `txid_root` or `txs`, an enum seems to be necessary.

2024-09-02 11:35 UTC, maciejka reviewed
get_block script is not updated because we want to supersede it with data based tests?

2024-09-02 11:35 UTC, maciejka commented on scripts/data/light_client_args_170.json
> +        "txs": [],
Seems redundant after recent changes.

2024-09-02 13:11 UTC, m-kus commented
> get_block script is not updated because we want to supersede it with data based tests?

Yes (but even if we want to still have integration tests in Cairo, it needs to be extended to construct chain state), left for a follow up task

2024-09-02 14:06 UTC, maciejka approved these changes

2024-09-02 14:24 UTC, merged