add bits_to_target
keep-starknet-strange/raito pull request #15
Opened 2024-08-01 01:07 UTC by harsh-ps-2003

- [x] issue #9 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [x] code change includes tests

Adds bits_to_target with a custom power method of u256, and uses it to validate_target

2024-08-02 08:12 UTC, maciejka commented
Where are the test cases?

2024-08-02 08:13 UTC, maciejka reviewed
Where are the test cases?

2024-08-02 08:32 UTC, harsh-ps-2003 commented
> Where are the test cases?

Will be adding them later today most probably! Suddenly got busy with some work! Thanks for the patience

2024-08-05 08:27 UTC, maciejka requested changes
Please squash prs #15 and #16.

2024-08-05 08:27 UTC, maciejka commented on src/engine.cairo
> +        while i < shift {
why don't you just use `div` here?

2024-08-05 08:27 UTC, maciejka commented on src/engine.cairo
> +pub fn bits_to_target(bits: u32) -> Result<u256, felt252> {
Implementation here: https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L178 looks much simpler. It seems there is no need to use loops.

2024-08-05 08:27 UTC, maciejka commented on tests/tests.cairo
> +use raito::engine::bits_to_target;
Use test cases from: https://github.com/ZeroSync/ZeroSync/blob/main/tests/unit/block/test_bits_and_target.json

2024-08-06 20:13 UTC, maciejka commented
How are you? Is there any progress? There are other issues waiting for this one to finish...

2024-08-07 00:11 UTC, harsh-ps-2003 commented
Will pick this up today again! Thanks for the patience

2024-08-07 01:42 UTC, harsh-ps-2003 commented
Can you squash merge the #15 and #16 ?

2024-08-07 11:05 UTC, harsh-ps-2003 commented
@maciejka resolving the conflicts is a mess as the project changed quite a lot! can I close both PRs and open 1 new one with all the changes instead!

2024-08-07 12:47 UTC, maciejka approved these changes

2024-08-07 12:50 UTC, maciejka commented
Fix fmt and tests, please.

2024-08-07 14:08 UTC, maciejka commented
> @maciejka suddenly I get error
> 
> ```
> Error: `scarb metadata` exited with error
> 
> stdout:
> error: failed to lookup for `cairo_test ^2.7.0` in registry: registry+https://there-is-no-default-registry-yet.com/
> ```
> 
> when trying to run `scarb test` locally!

Please ask on scarb tg channel: https://t.me/+1pMLtrNj5NthZWJk

2024-08-07 14:10 UTC, maciejka requested changes

2024-08-07 14:10 UTC, maciejka commented on src/utils.cairo
> +        return 1.into();
just 1_u256

2024-08-07 14:10 UTC, maciejka commented on src/utils.cairo
> +    let mut res: u256 = 1.into();
same here

2024-08-07 19:31 UTC, maciejka approved these changes

2024-08-07 19:32 UTC, maciejka commented
@harsh-ps-2003 please fix conflicts

2024-08-08 01:43 UTC, harsh-ps-2003 commented
Thanks for the patience!

2024-08-08 08:04 UTC, merged