transaction fee implementation
keep-starknet-strange/raito pull request #56
Opened 2024-08-11 20:46 UTC by stevencartavia

- [x] issue #39 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

Created the transaction fee function and updated OutPoint to have the amount.

2024-08-12 08:45 UTC, maciejka requested changes
A unit test would help.

2024-08-12 08:45 UTC, maciejka commented on src/validation.cairo
> +        while i < inputs.len() {
Arrays should be iterated over with `pop_front`, for example: 
```
while let Option::Some(x) = arr.pop_front() {
  sum += x;
};
```

2024-08-12 08:45 UTC, maciejka commented on src/validation.cairo
> +            let amount = (*inputs.at(i).previous_output.amount).into();
No need for `into`.

2024-08-12 08:45 UTC, maciejka commented on src/validation.cairo
> +        tx_fee.into()
No need for `into`.

2024-08-12 13:05 UTC, maciejka commented on src/validation.cairo
> +        while i < inputs.len() {
or even better, you can use `for` loop:
```
    for element in a {
        println!("the value is: {element}");
    }
```

2024-08-13 04:30 UTC, stevencartavia commented on src/utils.cairo
I copied and pasted this in here because I couldn't find a way to import and use them from tests/utils

2024-08-13 04:33 UTC, stevencartavia commented on src/utils.cairo
> +
I copied and pasted this in here because I couldn't find a way to bring them from tests/utils

2024-08-13 08:42 UTC, maciejka requested changes
Just small nit.

2024-08-13 08:42 UTC, maciejka commented on src/validation.cairo
> +        let tx_fee = TransactionValidatorImpl::fee(@tx_fee);
Naming conflict, how about `tx` and `fee` instead of `tx_fee` for both?

2024-08-13 08:47 UTC, maciejka approved these changes

2024-08-13 08:47 UTC, merged