[feat] Python version of script genrerate block data
keep-starknet-strange/raito pull request #67
Opened 2024-08-13 13:19 UTC by lomasson

- [x] issue #28
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/raito/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests

2024-08-13 17:09 UTC, maciejka requested changes
In python function names should be in snake_case, iirc.

2024-08-13 17:09 UTC, maciejka commented on scripts/data/get_block.py
> +def Txs(txsraw, blockHash, ntx):
lowercase?

2024-08-13 17:09 UTC, maciejka commented on scripts/data/get_block.py
> +    block = requestRPC("getblock", [blockHash])
If you set verbose = 2 (second optional parameter) getblock result will include all block transactions.

2024-08-13 17:09 UTC, maciejka commented on scripts/data/get_block.py
> +        blockHash = input("Enter block hash: ")
It should return error in this case

2024-08-13 17:10 UTC, maciejka commented
And please update get_blocks.sh

2024-08-13 18:10 UTC, lomasson commented on scripts/data/get_block.py
> +                        value: {str(int(txoutput["value"] * 100000000))}_64,
it's for rounding to int, because there's always a comma after the mutilation. but i'll try to remove

2024-08-15 11:56 UTC, m-kus commented on scripts/data/get_block.py
> +                                    amount: 0,
I think `gettxout` is more suitable

2024-08-15 11:57 UTC, m-kus commented on scripts/data/get_block.py
> +def requestRPC(method, params):
Here and after: function and variable names should be in snake case in Python

2024-08-16 14:27 UTC, lomasson commented
@maciejka @m-kus Is it useful to update get_block.sh ? with the `Python` version, is it useful to keep two versions of the same script, and basically the `Python` version wasn't intended to replace the `sh` / `jq` version ?

2024-08-16 18:30 UTC, m-kus commented
> @maciejka @m-kus Is it useful to update get_block.sh ? with the `Python` version, is it useful to keep two versions of the same script, and basically the `Python` version wasn't intended to replace the `sh` / `jq` version ?

Yes, keep both scripts for now (we will remove the bash one later once it's obsolete)

2024-08-18 19:35 UTC, closed without merging